#!/bin/sh
set -eu

( cd $HOME;
    yadm submodule update --recursive --init )

if ! command -v brew >/dev/null; then
    curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | sh
fi

if [ -f "$HOME/.Brewfile" ]; then
    brew bundle --file "$HOME/.Brewfile"
fi

if command -v nvim >/dev/null; then
    nvim '+Lazy update' '+quitall'
fi

if command -v tmux >/dev/null; then
    sh "$HOME/.tmux/plugins/tpm/bin/install_plugins"
fi

if command -v bat >/dev/null; then
    curl -fsSL -O --create-dirs \
        --output-dir "$HOME/.config/bat/themes" \
        https://raw.githubusercontent.com/rose-pine/tm-theme/refs/heads/main/dist/themes/rose-pine.tmTheme
    bat cache --build
fi
