#!/bin/sh
set -eu

if ! command -v brew >/dev/null; then
    curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | sh
fi

if [ -f "$HOME/.Brewfile" ]; then
    brew bundle --file "$HOME/.Brewfile"
fi

if command -v nvim >/dev/null; then
    nvim '+Lazy update' '+Lazy clean' '+Lazy install' '+quitall'
fi
